# Generated by Django 5.2.9 on 2025-12-07 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('source_type', models.CharField(choices=[('linkedin', 'LinkedIn'), ('reddit', 'Reddit'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('start_urls', models.JSONField(default=list, help_text='List of seed URLs to start crawling from')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Source-specific filters (tags, subreddits, etc.)')),
                ('requests_per_minute', models.PositiveIntegerField(default=10, help_text='Max requests per minute for this source')),
                ('crawl_interval_hours', models.PositiveIntegerField(default=24, help_text='Hours between automated crawls')),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('credentials_key', models.CharField(blank=True, help_text='Key to look up credentials in secrets store', max_length=100)),
                ('max_pages', models.PositiveIntegerField(default=100, help_text='Max pages to crawl per job')),
                ('follow_links', models.BooleanField(default=True, help_text='Whether to follow discovered links')),
                ('use_browser', models.BooleanField(default=False, help_text='Use headless browser instead of HTTP client')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'ordering': ['domain', 'name'],
                'indexes': [models.Index(fields=['enabled', 'source_type'], name='sources_sit_enabled_d59ca3_idx'), models.Index(fields=['last_crawl_at'], name='sources_sit_last_cr_aaadf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the job was scheduled to run')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('triggered_by', models.CharField(default='manual', help_text='scheduler, manual, api, etc.', max_length=50)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Aggregate stats: pages_crawled, leads_found, errors, etc.')),
                ('error_message', models.TextField(blank=True)),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='sources.siteconfig')),
            ],
            options={
                'verbose_name': 'Crawl Job',
                'verbose_name_plural': 'Crawl Jobs',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('leads_found', models.PositiveIntegerField(default=0)),
                ('links_discovered', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sources.crawljob')),
            ],
            options={
                'verbose_name': 'Crawl Log',
                'verbose_name_plural': 'Crawl Logs',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['crawl_job', 'http_status'], name='sources_cra_crawl_j_7eca1b_idx'), models.Index(fields=['crawl_job', '-fetched_at'], name='sources_cra_crawl_j_6e48ed_idx'), models.Index(fields=['http_status'], name='sources_cra_http_st_c5b152_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status', 'scheduled_at'], name='sources_cra_status_a70933_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['site_config', 'status'], name='sources_cra_site_co_deaec4_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['-started_at'], name='sources_cra_started_893875_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['-finished_at'], name='sources_cra_finishe_a2dbf9_idx'),
        ),
    ]
