# Generated by Django 5.2.9 on 2025-12-07 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('profile_url', models.URLField(max_length=2048)),
                ('source_domain', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Tags for categorizing leads (e.g., 'music-production', 'audio-engineering')", size=None)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_domain', 'created_at'], name='leads_lead_source__50430c_idx'), models.Index(fields=['email'], name='leads_lead_email_f663dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile_url', 'source_domain'), name='unique_lead_per_source')],
            },
        ),
    ]
